# Generated by Django 4.1.7 on 2023-03-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_posts_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
    ]
